# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxctl < Formula
  desc ""
  homepage "https://github.com/bytewax/waxctl-downloads"
  version "0.6.0"

  on_macos do
    url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.6.0/waxctl_0.6.0_darwin_all.tar.gz"
    sha256 "f9493e797f91d9f10c4717f178ea2adbd3dad82904252bc6a3af16efccd957da"

    def install
      bin.install "waxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.6.0/waxctl_0.6.0_linux_arm64.tar.gz"
      sha256 "fd286aeb4b8c4ce46a8eff6f0ab946d4d4139d08eed12658f957596e92a08416"

      def install
        bin.install "waxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.6.0/waxctl_0.6.0_linux_amd64.tar.gz"
      sha256 "8ae058d0d0663d775e1ae0f3daf0cd39f7ce5fc7051cb0f3b1e4acb0beed35f6"

      def install
        bin.install "waxctl"
      end
    end
  end
end
