# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxctl < Formula
  desc ""
  homepage "https://github.com/bytewax/waxctl-downloads"
  version "0.7.1"

  on_macos do
    url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.7.1/waxctl_0.7.1_darwin_all.tar.gz"
    sha256 "376d02a34b72f2820842a3f00e83b997477859d900a63d8ba3f726253315474b"

    def install
      bin.install "waxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.7.1/waxctl_0.7.1_linux_arm64.tar.gz"
      sha256 "7454eed8c2382fdb5048baa629d3863c92594a2390ef5de2af90fdb3092062be"

      def install
        bin.install "waxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bytewax/waxctl-downloads/releases/download/v0.7.1/waxctl_0.7.1_linux_amd64.tar.gz"
      sha256 "6eb3426da2605bd1b0e9d9cadbca73429af08fea501ad5501f6cee432f13849e"

      def install
        bin.install "waxctl"
      end
    end
  end
end
